### ISSUE TITLE
Review package compatibility

### ISSUE THREAD

**Issue by uranusjr** [MacDownApp/macdown-site#16]
Netlify informs me that a recent build is failing: ([full log in Gist](https://gist.github.com/uranusjr/00dc3ead34d373f49cd6b920d33beae0))

```
3:03:39 PM: Traceback (most recent call last):
3:03:39 PM:   File "/opt/buildhome/python2.7/bin/invoke", line 10, in <module>
3:03:39 PM:     sys.exit(program.run())
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/invoke/program.py", line 384, in run
3:03:39 PM:     self.execute()
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/invoke/program.py", line 566, in execute
3:03:39 PM: executor.execute(*self.tasks)
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/invoke/executor.py", line 129, in execute
3:03:39 PM:     result = call.task(*args, **call.kwargs)
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/invoke/tasks.py", line 127, in __call__
3:03:39 PM:     result = self.body(*args, **kwargs)
3:03:39 PM:   File "/opt/build/repo/tasks.py", line 119, in build
3:03:39 PM:     lektor_cli_ctx.load_plugins()
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/lektor/cli.py", line 131, in load_plugins
3:03:39 PM:     initialize_plugins(self.get_env())
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/lektor/pluginsystem.py", line 122, in initialize_plugins
3:03:39 PM:     plugins = load_plugins()
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/lektor/pluginsystem.py", line 116, in load_plugins
3:03:39 PM:     rv[ep.name] = ep.load()
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
3:03:39 PM:     return self.resolve()
3:03:39 PM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
3:03:39 PM:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
3:03:39 PM:   File "/opt/build/repo/packages/lektor-atom/lektor_atom.py", line 22, in <module>
3:03:39 PM:     from werkzeug.contrib.atom import AtomFeed
3:03:39 PM: ImportError: No module named contrib.atom
```

Not sure what the problem is atm.

**Comment by FranklinYu** [comment]
I suspect that we didn’t freeze the package version.

**Comment by FranklinYu** [comment]
Quote from https://werkzeug.palletsprojects.com/en/0.16.x/contrib/atom/

> Deprecated since version 0.15: This will be removed in version 1.0. Use a dedicated feed library instead.

Would you recommend fixing version at `< 1.0` or finding an atom library?

**Comment by uranusjr** [comment]
Yeah, sounds good to me.

**Comment by FranklinYu** [comment]
That was a choice… I assume you mean fixing version?

**Comment by uranusjr** [comment]
Oh I totally missed the second part LOL, sorry.

I was saying that it’s a good idea to simply fix the version. We are not using much of werkzeug at all anyway.
